# Generated by Django 5.2.5 on 2025-10-21 13:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_paystacktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacktransaction',
            name='reference',
            field=models.CharField(default=accounts.models.PaystackTransaction.generate_ref, max_length=20, unique=True),
        ),
    ]
