# Generated by Django 5.2.5 on 2025-10-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_paystacktransaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistanttask',
            name='failed_reason',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('reserve', 'Reserve'), ('refund', 'Refund'), ('deduct', 'Deduct')], max_length=32),
        ),
    ]
