# Generated by Django 5.2.5 on 2025-10-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_aiassistanttask_failed_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credittransaction',
            name='related',
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='AI_staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
