# Generated by Django 5.2.5 on 2025-09-14 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_officecity_citylobby_alter_office_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='office',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office',
            name='public_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='office',
            name='services',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='officecity',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officecity',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officecity',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='workspace.officecity'),
        ),
        migrations.AddField(
            model_name='room',
            name='height',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='room',
            name='width',
            field=models.FloatField(default=150),
        ),
        migrations.AddField(
            model_name='room',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='office',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices_city', to='workspace.officecity'),
        ),
        migrations.AlterField(
            model_name='officecity',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='workspace.office'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('office', 'user', 'city')},
        ),
    ]
