# Generated by Django 5.2.5 on 2025-09-14 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_presence_unique_together_office_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices', to='workspace.officecity'),
        ),
    ]
