# Generated by Django 5.2.5 on 2025-09-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_alter_office_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
