# Generated by Django 5.2.5 on 2025-09-17 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_room_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('receptionist', 'Receptionist')], max_length=50)),
                ('is_visitor', models.BooleanField(default=False)),
                ('assigned_rooms', models.ManyToManyField(related_name='workers', to='workspace.room')),
                ('can_visit_rooms', models.ManyToManyField(blank=True, related_name='accessible_workers', to='workspace.room')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='workspace.office')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
