# Generated by Django 5.2.5 on 2025-09-18 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='can_visit_rooms',
            new_name='accessible_rooms',
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('receptionist', 'Receptionist'), ('admin', 'Admin')], default='staff', max_length=50),
        ),
        migrations.CreateModel(
            name='VisitorAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_access', to='workspace.office')),
                ('rooms', models.ManyToManyField(blank=True, to='workspace.room')),
            ],
        ),
    ]
