# Generated by Django 5.2.5 on 2025-09-19 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_rename_can_visit_rooms_worker_accessible_rooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='assigned_rooms',
            new_name='rooms',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='accessible_rooms',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_visitor',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='role',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.AddField(
            model_name='worker',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='created_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
