# Generated by Django 5.2.5 on 2025-09-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_rename_assigned_rooms_worker_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_id',
            field=models.CharField(default='KO1-0001', editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
