# Generated by Django 5.2.5 on 2025-09-20 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_worker_worker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='workspace.worker')),
            ],
        ),
    ]
