# Generated by Django 5.2.5 on 2025-09-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_workerpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerpresence',
            name='last_logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
