# Generated by Django 5.2.5 on 2025-09-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0012_workerpresence_last_logout_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerpresence',
            old_name='is_online',
            new_name='is_presence',
        ),
    ]
