# Generated by Django 5.2.5 on 2025-09-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_rename_is_online_workerpresence_is_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='access_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='room',
            name='access_policy',
            field=models.CharField(choices=[('free', 'Free Access'), ('form', 'Form Required'), ('approval', 'Staff Approval'), ('locked', 'Access Code')], default='free', max_length=20),
        ),
    ]
