# Generated by Django 5.2.5 on 2025-09-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0015_visitoraccesssubmission_delete_visitoraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitoraccesssubmission',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitoraccesssubmission',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
