# Generated by Django 5.2.5 on 2025-09-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0016_visitoraccesssubmission_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='booking_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='office',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
