# Generated by Django 5.2.5 on 2025-09-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionistLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
