# Generated by Django 5.2.5 on 2025-10-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistaff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionistlog',
            name='office_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
