# Generated by Django 5.2.5 on 2025-10-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistaff', '0004_assistantlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantlog',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('meeting', 'Meeting'), ('note', 'Note'), ('resource', 'Resource'), ('file', 'File'), ('email', 'Email'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
