# Generated by Django 5.2.5 on 2025-10-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistaff', '0005_assistantlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantlog',
            name='subtype',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
