# Generated by Django 5.2.5 on 2025-10-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistaff', '0006_assistantlog_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantActionSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='assistantlog',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='aistaff.assistantactionsubtype'),
        ),
        migrations.AddField(
            model_name='assistantactionsubtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='aistaff.assistantactiontype'),
        ),
        migrations.AlterField(
            model_name='assistantlog',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='aistaff.assistantactiontype'),
        ),
        migrations.AlterUniqueTogether(
            name='assistantactionsubtype',
            unique_together={('type', 'name')},
        ),
    ]
