# Generated by Django 5.2.5 on 2025-10-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistaff', '0007_assistantactionsubtype_assistantactiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgentActionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_key', models.CharField(default='*', max_length=100)),
                ('action_key', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI Agent Action Cost',
                'verbose_name_plural': 'AI Agent Action Costs',
                'unique_together': {('agent_key', 'action_key')},
            },
        ),
    ]
