# Generated by Django 5.2.5 on 2025-10-30 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistaff', '0008_aiagentactioncost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(default='*', max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aiagentactioncost',
            name='agent_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_cost', to='aistaff.aiagent'),
        ),
    ]
