# Generated by Django 5.2.5 on 2025-11-01 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistaff', '0011_salesagentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsFollowUpRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('negotiateing', 'Negotiateing'), ('closed', 'Closed'), ('lost', 'Lost')], max_length=50, unique=True)),
                ('interval_hours', models.PositiveIntegerField(default=24)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='saleslead',
            old_name='last_contacted',
            new_name='last_follow_up',
        ),
        migrations.AddField(
            model_name='salesagentlog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleslead',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='next_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('negotiateing', 'Negotiateing'), ('closed', 'Closed'), ('lost', 'Lost')], default='new', max_length=50),
        ),
    ]
